import { getCharactersTotalTest } from "./getCharactersTotal.test.js";
import { getParagraphsTotalTest } from "./getParagraphsTotal.test.js";
import { getShortWordsTotalTest } from "./getShortWordsTotal.test.js";
import { getWordsListTest } from "./getWordsList.test.js";
import { getWordsTotalTest } from "./getWordsTotal.test.js";
import { getWordFrequencyTest } from "./getWordFrequency.test.js";
import { getReversedTextTest } from "./getReversedText.test.js";
import { getCensoredTextTest } from "./getCensoredText.test.js";
import { getCamelCaseTextTest } from "./getCamelCaseText.test.js";
import { getFilteredWordsTest } from "./getFilteredWords.test.js";

getParagraphsTotalTest();
getWordsTotalTest();
getCharactersTotalTest();
getShortWordsTotalTest();
getWordsListTest();
getWordFrequencyTest();
getReversedTextTest();
getCensoredTextTest();
getCamelCaseTextTest();
getFilteredWordsTest();
